# Generated by Django 5.0.2 on 2024-10-18 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
