# Generated by Django 5.0.2 on 2024-10-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytasks', '0002_todotask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='task_id',
            field=models.IntegerField(default=1),
        ),
    ]
