# Generated by Django 5.0.2 on 2024-10-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytasks', '0003_todotask_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='task_id',
        ),
    ]
